Corrected TF manifest
yandex-cloud-examples/yc-data-proc-spark-kafka pull request #3
Opened 2024-11-29 15:25 UTC by mikhaildoc-documentat

2024-12-28 05:01 UTC, Odyvia42 requested changes

2024-12-28 05:01 UTC, Odyvia42 commented on kafka-and-data-proc.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Тут было правильно. Давай вернём как было.

2025-01-09 10:15 UTC, mikhaildoc-documentat commented on kafka-and-data-proc.tf
> +      ssh_public_keys = ["${file(local.dp_ssh_key)}"]
Тут используется не явно прописанный путь, а локальная переменная, с ней путь нужно записывать именно так, как я исправил. См. пример в https://developer.hashicorp.com/terraform/language/functions/file

2025-01-10 05:23 UTC, Odyvia42 approved these changes

2025-01-10 13:54 UTC, lanieuszko approved these changes

2025-01-10 13:54 UTC, merged